version: '2'

services:
  backend:
    build: ./backend
    image: drunkery-back
    ports:
      -  3000
    networks:
      - drunkery
  frontend:
    build: ./frontend
    image: drunkery-front
    ports:
      - 3000
    volumes:
      - ./frontend:/drunkery
      - node_front:/drunkery/node_modules
    networks:
      - drunkery
  nginx:
    image: nginx
    depends_on:
      - frontend
      - backend
    volumes:
      - ./drunkery.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - drunkery

volumes:
  node_front:

networks:
  drunkery:
