version: '2'

services:
  backend:
    build: ./backend
    image: drunkery-back
    ports:
      - 3000:3000
    networks:
      - drunkery
  frontend:
    build: ./frontend
    image: drunkery-front
    ports:
      - 80:3000
    volumes:
      - ./frontend:/drunkery
      - node_front:/drunkery/node_modules
    networks:
      - drunkery
    command: [ npm, run, serve]
volumes:
  node_front:

networks:
  drunkery:
