version: '2'

services:
  backend:
    build: ./backend
    image: drunkery-back
    ports:
      - 3000:3000
    networks:
      - drunkery
  frontend:
    build: ./frontend
    image: drunkery-front
    networks:
      - drunkery
    command: [ npm, run, serve]
  nginx:
    image: nginx
    depends_on:
      - frontend
      - backend
    ports:
      - 80:80
    volumes:
      - ./drunkery.conf:/etc/nginx/conf.d/default.conf

    networks:
      - drunkery
volumes:
  node_front:

networks:
  drunkery:
